apiVersion: v1
kind: Namespace
metadata:
  name: testes
  labels: 
    app: exemplo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exemplo
  namespace: testes
  labels:
    app: exemplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exemplo
  template:
    metadata:
      labels:
        app: exemplo
    spec:
      containers:
      - name: exemplo
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: exemplo
  namespace: testes
  labels:
    app: exemplo
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30002
  selector:
    app: exemplo
